namespace: "crivetimihai"
name: "development"
version: "1.0.3"
readme: "README.md"
authors:
  - "Mihai Criveti (https://twitter.com/crivetimihai)"
description: "Collection of Workstation Tools"
license:
  - "MIT"
tags:
  - linux
  - development
  - baseline
  - profile
  - dotfiles
  - micro
  - pip
  - collection
repository: "https://www.github.com/crivetimihai/ansible_development"
homepage: "https://www.github.com/crivetimihai/ansible_development"
documentation: "https://www.github.com/crivetimihai/ansible_development"
issues: "https://www.github.com/crivetimihai/ansible_development/issues"
